name: My Sample (develop)

on:
  push:
    branches:
      - develop

jobs:
  deploy_develop:
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - uses: actions/github-script@v3
        id: write-json
        with:
          script: |
            return JSON.stringify({
              "project_id": "${{ vars.PROJECT_ID }}"
            }, 2)
          result-encoding: string
      - run: echo '${{steps.write-json.outputs.result}}' >> hoge.json
      - run: cat hoge.json
