name: My Sample

on:
  workflow_dispatch:

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - run: echo deploy develop
      - run: echo secret ${{ secrets.PROJECT_ID }}
  
  deploy_production:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - run: echo deploy production
      - run: echo secret ${{ secrets.PROJECT_ID }}
