name: My Sample (develop)

on:
  push:
    branches:
      - develop

jobs:
  deploy_develop:
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - run: echo deploy production
      - run: echo "{" >> hoge.json
      - run: echo '  "hoge" "${{ vars.PROJECT_ID }}"' >> hoge.json
      - run: echo "}" >> hoge.json
      - run: cat hoge.json
