name: My Sample (develop)

on:
  push:
    branches:
      - develop

jobs:
  deploy_develop:
    runs-on: ubuntu-latest
    environment:
      name: develop
    steps:
      - run: echo deploy production
      - run: echo vars ${{ vars.PROJECT_ID }}
