name: My Sample (production)

on:
  push:
    branches:
      - main

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - run: echo deploy production
      - run: echo secret ${{ secrets.PROJECT_ID }}
